### ISSUE TITLE
Items BASEUOM query

### ISSUE THREAD

**Issue by fdtaljaard** [Intacct/intacct-sdk-net#150] opened 2021-02-26 08:40 UTC
Error: XL03000006 The following fields cannot be queried: [ item: [BASEUOM] ] 

When I perform a ReadByQuery specifying BASEUOM on object ITEM the result is returned as per the code example below. When I perform a QueryFunction I get the above error.

**Return results with BASEUOM**
```
ReadByQuery read = new ReadByQuery()
                {
                    ObjectName = "ITEM",
                    Fields = { "BASEUOM", "RECORDNO", "ITEMID", "STATUS", "NAME", "WHENMODIFIED" },
                    PageSize = 1000,
                };
```

**Throw error:**
```
               SelectBuilder selectBuilder = new SelectBuilder();
                ISelect[] fields = selectBuilder.Fields(new[] { "BASEUOM", "RECORDNO", "ITEMID", "STATUS", "NAME", "WHENMODIFIED" }).GetFields();
                QueryFunction query = new QueryFunction()
                {
                    SelectFields = fields,
                    FromObject = "ITEM",
                    Filter = filter,
                    CaseInsensitive = false,
                    PageSize = 1000
                };
```

**Comment by karstenintacct** [comment] 2021-06-17 19:03
Hi,
The SDK behaves correctly. The problem is that BASEUOM is not queryable using the query function.
I will create a ticket to get this addressed.

Thank you
Karsten

**Comment by karstenintacct** [comment] 2021-06-17 20:23
I have created a ticket and left it with the application area.

I am going to close this issue, since it is not related to the SDK. Please open a customer support case, to get the API problem addressed. (this will give you an better insight on processing of this issue)

**Closed** 2021-06-17 20:26 UTC
